services:
    alterable_form.form_factory:
        class: Wuestkamp\AlterableFormBundle\Form\FormFactory
    alterable_form.form_alterator:
        class: Wuestkamp\AlterableFormBundle\Form\FormAlterator
        arguments: ['%alterable_form.configuration%']